[package]
name = "hashit"
version = "0.1.0"
edition = "2018"

[lib]
name = "hashit"
src = "src/lib.rs"

[[bin]]
name = "hashit"
src = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.4"
# Hashing algos
md-5 = "0.9.1"